language: cpp
sudo: required
dist: trusty

branches:
    only:
        - develop
        - /^develop-.*$/
        - master
        - release

before_install:
    - sudo apt-get update
    - sudo apt-get install python3 python3-pip
    - sudo pip3 install tabulate requests coloredlogs setuptools docutils

install:
    - python3 setup.py check -r -s
    - python3 setup.py sdist
    - ./tcore bootstrap
    - ./tcore fetch

script:
    - ./tcore init --remote https://github.com/theCore-embedded/example_hello_world
    - cd example_hello_world
    - ../tcore compile --list
    - ../tcore compile --target host --buildtype release
    - ../tcore compile --target stm32f4_disc --buildtype debug
    - ../tcore flash --list-bin
    - ../tcore runenv --sudo "echo TEST FINISHED"


